services:
  question-service:
    build:
      context: ./question-service
      dockerfile: Dockerfile
    ports:
      - "8002:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - quiz-network
    restart: unless-stopped

  quiz-service:
    build:
      context: ./quiz-service
      dockerfile: Dockerfile
    ports:
      - "8001:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - question-service
    networks:
      - quiz-network
    restart: unless-stopped

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8003:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - question-service
      - quiz-service
    networks:
      - quiz-network
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - quiz-service
      - question-service
    networks:
      - quiz-network
    volumes:
      - frontend_data:/app
    restart: unless-stopped

networks:
  quiz-network:
    driver: bridge

volumes:
  frontend_data:
