services:
  question-service:
    container_name: question-service1
    build:
      context: ./question-service
      dockerfile: Dockerfile
    ports:
      - "8002:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - quiz-network
      

  quiz-service:
    container_name: quiz-service1
    build:
      context: ./quiz-service
      dockerfile: Dockerfile
    ports:
      - "8001:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - question-service
    networks:
      - quiz-network

  user-service:
    container_name: user-service1
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8003:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - question-service
      - quiz-service
      - frontend
    networks:
      - quiz-network

  frontend:
    container_name: frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80" # 3000 på host -> 80 i Nginx
    depends_on:
      - quiz-service
      - question-service
    networks:
      - quiz-network
    volumes:
      - ../frontend:/app  # Frontend kan beholde volumet for hot-reloading

networks:
  quiz-network:
    driver: bridge
